channels:
  - adl/label/dev
  - conda-forge
  - r
  - defaults
  - bfurneaux
dependencies:
  - python=3.6
  - spot=2.7.4.dev.55
  - graphviz
  - r-irkernel
  - r-ggplot2
  - r-tidyverse
  - r-tikzdevice
  - pandas
  - scipy

